application: dvlahack
version: 2
runtime: php55
api_version: 1

handlers:

- url: /mobile/thanks.php
  script: /mobile/thanks.php

- url: /images
  static_dir: mobile/images

- url: /styles
  static_dir: styles

- url: /drivers
  script: drivers.php

- url: /mobile/rankCar.php
  script: /mobile/rankCar.php

- url: /mobile/rankDriver.php
  script: /mobile/rankDriver.php

- url: /mobile/rankPassenger.php
  script: /mobile/rankPassenger.php

- url: /.*
  script: index.php
